import { Router, Request, Response } from 'express';
import { FullScanReport } from '@weblens/shared';

export function createDemoRouter(): Router {
  const router = Router();

  router.get('/', (_req: Request, res: Response) => {
    const demoReport: FullScanReport = {
      scan: {
        id: 'demo-sample-scan-8f3k2m',
        url: 'https://demo.weblens.app',
        normalizedUrl: 'https://demo.weblens.app',
        domain: 'demo.weblens.app',
        status: 'completed',
        overallScore: 92,
        stage: 'completed',
        progress: 100,
        screenshotUrl: null,
        startedAt: new Date(Date.now() - 120000).toISOString(),
        completedAt: new Date().toISOString(),
        createdAt: new Date(Date.now() - 120000).toISOString(),
      },
      overall: {
        score: 92,
        rating: 'excellent',
        summaryText: 'Your website is in excellent health, with only 4 minor improvements suggested.',
        categoryScores: {
          performance: {
            scanId: 'demo-sample-scan-8f3k2m',
            category: 'performance',
            score: 94,
            rating: 'excellent',
            weight: 0.25,
            issuesCount: { critical: 0, high: 0, medium: 1, low: 0, passed: 5 },
            createdAt: new Date().toISOString(),
          },
          seo: {
            scanId: 'demo-sample-scan-8f3k2m',
            category: 'seo',
            score: 88,
            rating: 'good',
            weight: 0.20,
            issuesCount: { critical: 0, high: 1, medium: 1, low: 0, passed: 6 },
            createdAt: new Date().toISOString(),
          },
          accessibility: {
            scanId: 'demo-sample-scan-8f3k2m',
            category: 'accessibility',
            score: 96,
            rating: 'excellent',
            weight: 0.20,
            issuesCount: { critical: 0, high: 0, medium: 1, low: 0, passed: 5 },
            createdAt: new Date().toISOString(),
          },
          security: {
            scanId: 'demo-sample-scan-8f3k2m',
            category: 'security',
            score: 91,
            rating: 'excellent',
            weight: 0.15,
            issuesCount: { critical: 0, high: 0, medium: 1, low: 1, passed: 6 },
            createdAt: new Date().toISOString(),
          },
          mobile: {
            scanId: 'demo-sample-scan-8f3k2m',
            category: 'mobile',
            score: 90,
            rating: 'excellent',
            weight: 0.10,
            issuesCount: { critical: 0, high: 0, medium: 0, low: 1, passed: 3 },
            createdAt: new Date().toISOString(),
          },
          best_practices: {
            scanId: 'demo-sample-scan-8f3k2m',
            category: 'best_practices',
            score: 93,
            rating: 'excellent',
            weight: 0.10,
            issuesCount: { critical: 0, high: 0, medium: 0, low: 0, passed: 5 },
            createdAt: new Date().toISOString(),
          },
        },
        totalIssues: {
          critical: 0,
          high: 1,
          medium: 4,
          low: 2,
          passed: 30,
        },
      },
      categories: {
        performance: {
          score: 94,
          rating: 'excellent',
          metrics: [
            { id: 'lcp', name: 'Largest Contentful Paint (LCP)', value: '1.4s', status: 'good', description: 'Measures visual load stability' },
            { id: 'fcp', name: 'First Contentful Paint (FCP)', value: '0.8s', status: 'good', description: 'Initial render time' },
            { id: 'cls', name: 'Cumulative Layout Shift (CLS)', value: '0.02', status: 'good', description: 'Visual stability score' },
            { id: 'ttfb', name: 'Time to First Byte (TTFB)', value: '180ms', status: 'good', description: 'Server response time' },
          ],
          issues: [
            {
              scanId: 'demo-sample-scan-8f3k2m',
              category: 'performance',
              ruleId: 'perf.text-compression',
              severity: 'medium',
              title: 'Enable Brotli compression on 2 font assets',
              description: '2 WOFF2 font files were served with gzip instead of optimal Brotli compression.',
              impact: 'Slightly larger initial font download payload.',
              recommendation: 'Configure your web server to serve .woff2 with Brotli encoding.',
              technicalDetails: 'Assets: /fonts/inter-bold.woff2, /fonts/inter-regular.woff2',
              passed: false,
              scoreImpact: 6,
            },
            {
              scanId: 'demo-sample-scan-8f3k2m',
              category: 'performance',
              ruleId: 'perf.lcp-fast',
              severity: 'passed',
              title: 'Largest Contentful Paint is ultra fast (1.4s)',
              description: 'LCP is well within the green threshold (< 2.5s).',
              impact: 'Exceptional visual rendering speed for users.',
              recommendation: 'Maintain existing CDN caching.',
              passed: true,
              scoreImpact: 0,
            },
          ],
        },
        seo: {
          score: 88,
          rating: 'good',
          metrics: [
            { id: 'seo.title', name: 'Title Length', value: '42 characters', status: 'good', description: 'Page title in SERPs' },
            { id: 'seo.meta_description', name: 'Meta Description', value: 'Missing', status: 'needs_improvement', description: 'Snippet description' },
            { id: 'seo.h1_count', name: 'H1 Headings', value: '1 found', status: 'good', description: 'Primary topic signal' },
          ],
          issues: [
            {
              scanId: 'demo-sample-scan-8f3k2m',
              category: 'seo',
              ruleId: 'seo.missing-meta-description',
              severity: 'high',
              title: 'Missing meta description',
              description: 'No <meta name="description"> tag was found in the <head>.',
              impact: 'Search engines will auto-generate snippets from page body, hurting click-through rate.',
              recommendation: 'Add a concise 120-155 character meta description.',
              technicalDetails: '<meta name="description" content="WebLens is an instant website audit tool.">',
              location: '<head>',
              passed: false,
              scoreImpact: 10,
            },
            {
              scanId: 'demo-sample-scan-8f3k2m',
              category: 'seo',
              ruleId: 'seo.title-optimal',
              severity: 'passed',
              title: 'Page title is optimal (42 characters)',
              description: 'Title is descriptive and fits standard SERP width.',
              impact: 'Renders cleanly in Google search results.',
              recommendation: 'Maintain keyword focus.',
              passed: true,
              scoreImpact: 0,
            },
          ],
        },
        accessibility: {
          score: 96,
          rating: 'excellent',
          metrics: [
            { id: 'a11y.image_alt', name: 'Image Alt Coverage', value: '8 / 9', status: 'needs_improvement', description: 'Alt text presence' },
            { id: 'a11y.landmarks', name: 'HTML5 Landmarks', value: 'Complete', status: 'good', description: 'Semantic structure' },
          ],
          issues: [
            {
              scanId: 'demo-sample-scan-8f3k2m',
              category: 'accessibility',
              ruleId: 'a11y.missing-alt',
              severity: 'medium',
              title: '1 image is missing an alt attribute',
              description: 'An illustration image in the footer lacks alt description.',
              impact: 'Screen readers announce filename instead of context.',
              recommendation: 'Add alt="" if decorative or alt="Partner logos" if informative.',
              technicalDetails: '<img src="/assets/footer-graphic.svg" />',
              location: '<footer><img>',
              passed: false,
              scoreImpact: 4,
            },
            {
              scanId: 'demo-sample-scan-8f3k2m',
              category: 'accessibility',
              ruleId: 'a11y.unique-ids',
              severity: 'passed',
              title: 'All element IDs are unique',
              description: 'Zero duplicate IDs found across the DOM.',
              impact: 'Ensures ARIA landmarks and focus management function properly.',
              recommendation: 'Keep unique ID scoping.',
              passed: true,
              scoreImpact: 0,
            },
          ],
        },
        security: {
          score: 91,
          rating: 'excellent',
          metrics: [
            { id: 'sec.https', name: 'HTTPS Protocol', value: 'Active (TLS 1.3)', status: 'good', description: 'Encrypted communication' },
            { id: 'sec.hsts', name: 'HSTS Header', value: 'Enabled', status: 'good', description: 'Strict transport security' },
            { id: 'sec.csp', name: 'Content-Security-Policy', value: 'Missing', status: 'needs_improvement', description: 'Script source controls' },
          ],
          issues: [
            {
              scanId: 'demo-sample-scan-8f3k2m',
              category: 'security',
              ruleId: 'sec.missing-csp',
              severity: 'medium',
              title: 'Missing Content-Security-Policy (CSP) header',
              description: 'No CSP header was detected on the response.',
              impact: 'Leaves site more exposed to Cross-Site Scripting (XSS) if user inputs are reflected.',
              recommendation: 'Add a baseline Content-Security-Policy header.',
              technicalDetails: "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline';",
              location: 'HTTP Headers',
              passed: false,
              scoreImpact: 9,
            },
            {
              scanId: 'demo-sample-scan-8f3k2m',
              category: 'security',
              ruleId: 'sec.https-active',
              severity: 'passed',
              title: 'HTTPS & TLS 1.3 enforced',
              description: 'Valid certificate with 240 days remaining.',
              impact: 'Guarantees confidentiality and message integrity.',
              recommendation: 'Continue auto-renewal.',
              passed: true,
              scoreImpact: 0,
            },
          ],
        },
        mobile: {
          score: 90,
          rating: 'excellent',
          metrics: [
            { id: 'mobile.viewport', name: 'Viewport Configuration', value: 'Configured', status: 'good', description: 'Mobile responsive meta' },
          ],
          issues: [
            {
              scanId: 'demo-sample-scan-8f3k2m',
              category: 'mobile',
              ruleId: 'mobile.no-responsive-images',
              severity: 'low',
              title: 'Consider using responsive srcset on hero banner',
              description: 'Hero image uses standard src without srcset for high-DPI displays.',
              impact: 'Suboptimal resolution adaptation on mobile screens.',
              recommendation: 'Add srcset with 1x and 2x image variants.',
              passed: false,
              scoreImpact: 4,
            },
            {
              scanId: 'demo-sample-scan-8f3k2m',
              category: 'mobile',
              ruleId: 'mobile.no-overflow',
              severity: 'passed',
              title: 'Zero horizontal layout overflow',
              description: 'Layout scales cleanly across all viewport widths.',
              impact: 'Prevents unwanted horizontal scrolling on mobile.',
              recommendation: 'Keep max-width: 100% on wide elements.',
              passed: true,
              scoreImpact: 0,
            },
          ],
        },
        best_practices: {
          score: 93,
          rating: 'excellent',
          metrics: [
            { id: 'bp.doctype', name: 'HTML5 Doctype', value: 'Valid HTML5', status: 'good', description: 'Standard rendering mode' },
            { id: 'bp.js_errors', name: 'JavaScript Errors', value: 'None', status: 'good', description: 'Console exceptions' },
          ],
          issues: [
            {
              scanId: 'demo-sample-scan-8f3k2m',
              category: 'best_practices',
              ruleId: 'bp.doctype-present',
              severity: 'passed',
              title: 'Valid HTML5 doctype',
              description: 'Document standard is properly declared on line 1.',
              impact: 'Ensures standards-compliant browser layout.',
              recommendation: 'Keep doctype intact.',
              passed: true,
              scoreImpact: 0,
            },
            {
              scanId: 'demo-sample-scan-8f3k2m',
              category: 'best_practices',
              ruleId: 'bp.no-console-errors',
              severity: 'passed',
              title: 'Zero JavaScript runtime errors',
              description: 'Clean console execution without uncaught exceptions.',
              impact: 'High software stability and reliability.',
              recommendation: 'Continue test automation.',
              passed: true,
              scoreImpact: 0,
            },
          ],
        },
      },
      resources: [
        { scanId: 'demo-sample-scan-8f3k2m', url: 'https://demo.weblens.app/', resourceType: 'document', sizeBytes: 18450, loadTimeMs: 180, statusCode: 200, isCompressed: true, isCached: false },
        { scanId: 'demo-sample-scan-8f3k2m', url: 'https://demo.weblens.app/assets/main.css', resourceType: 'stylesheet', sizeBytes: 32400, loadTimeMs: 95, statusCode: 200, isCompressed: true, isCached: true },
        { scanId: 'demo-sample-scan-8f3k2m', url: 'https://demo.weblens.app/assets/bundle.js', resourceType: 'script', sizeBytes: 112000, loadTimeMs: 140, statusCode: 200, isCompressed: true, isCached: true },
        { scanId: 'demo-sample-scan-8f3k2m', url: 'https://demo.weblens.app/assets/hero.webp', resourceType: 'image', sizeBytes: 142000, loadTimeMs: 220, statusCode: 200, isCompressed: false, isCached: true },
        { scanId: 'demo-sample-scan-8f3k2m', url: 'https://demo.weblens.app/fonts/inter.woff2', resourceType: 'font', sizeBytes: 28000, loadTimeMs: 80, statusCode: 200, isCompressed: true, isCached: true },
      ],
      resourceBreakdown: {
        totalCount: 5,
        totalSizeBytes: 332850,
        totalLoadTimeMs: 220,
        byType: {
          document: { count: 1, sizeBytes: 18450 },
          script: { count: 1, sizeBytes: 112000 },
          stylesheet: { count: 1, sizeBytes: 32400 },
          image: { count: 1, sizeBytes: 142000 },
          font: { count: 1, sizeBytes: 28000 },
          media: { count: 0, sizeBytes: 0 },
          fetch: { count: 0, sizeBytes: 0 },
          xhr: { count: 0, sizeBytes: 0 },
          other: { count: 0, sizeBytes: 0 },
        },
      },
    };

    return res.json(demoReport);
  });

  return router;
}
